#!/bin/bash
# Generates the .clangd IntelliSense config at the repo root.
#
# .clangd needs absolute, machine-specific paths (clangd resolves relative -I
# flags against the inferred command's working directory, not the repo root),
# so the file is gitignored and each user regenerates it locally with this
# script. Re-run it after adding a new include/ subdirectory — and add the new
# directory to the list below, mirroring CMakeLists.txt.

# Fail fast: -e exits on any error, -u errors on undefined vars,
# pipefail propagates failures through pipes.
set -euo pipefail

# Resolve paths relative to this script, not the caller's working directory,
# so the script works no matter where it's invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Homebrew lives at /opt/homebrew on Apple Silicon and /usr/local on Intel;
# `brew --prefix` resolves the right one. The keg-only formulas (libomp,
# libpq) are addressed via their own prefixes rather than <prefix>/opt/... so
# the script also works if they were installed elsewhere.
BREW_PREFIX="$(brew --prefix)"
LIBOMP_PREFIX="$(brew --prefix libomp)"
LIBPQ_PREFIX="$(brew --prefix libpq)"

# Where the XCTest framework lives for the active Xcode installation.
XCODE_FRAMEWORKS="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/Library/Frameworks"

OUTPUT="$REPO_ROOT/.clangd"

cat > "$OUTPUT" <<EOF
# clangd IntelliSense config — generated by scripts/generate_clangd.sh; edit
# that script (not this file) and re-run it.
# The XCTest tests (tests/*.mm) are built by Xcode, not CMake, so they have no
# entry in build/compile_commands.json. Without flags, clangd can't find the
# XCTest framework or project headers. These flags mirror what CMake emits in
# build/compile_commands.json, scoped to the .mm test files.
#
# NOTE: paths must be absolute. clangd resolves a relative -I against the
# inferred command's working directory (build/external/libpqxx/src), not the
# repo root, so relative paths break header resolution. This file is therefore
# machine-specific and gitignored.
If:
  PathMatch: .*\.mm
CompileFlags:
  Add:
    - -xobjective-c++
    - -std=gnu++2b
    - -F$XCODE_FRAMEWORKS
    # Project headers (include/ and its subdirs — tests use bare #import "x.hpp")
    - -I$REPO_ROOT/include
    - -I$REPO_ROOT/include/commands
    - -I$REPO_ROOT/include/models
    - -I$REPO_ROOT/include/reporting
    - -I$REPO_ROOT/include/strategies
    - -I$REPO_ROOT/include/sweep
    - -I$REPO_ROOT/include/trading
    - -I$REPO_ROOT/include/trading_definitions
    - -I$REPO_ROOT/include/utilities
    # Third-party headers
    - -I$REPO_ROOT/external
    - -I$REPO_ROOT/external/boost-decimal/include
    - -I$REPO_ROOT/external/libpqxx/include
    - -I$REPO_ROOT/build/external/libpqxx/include
    - -I$LIBOMP_PREFIX/include
    - -isystem$BREW_PREFIX/include
    - -isystem$LIBPQ_PREFIX/include
    - -isystem$LIBPQ_PREFIX/include/postgresql/server
EOF

echo "Wrote $OUTPUT"
