on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Build

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed

jobs:

  build:
    name: Build & Test
    runs-on: macos-26.2

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Homebrew package manager
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    # Step 3: Install required dependencies using Homebrew
    - name: Install dependencies
      run: bash ./.github/workflows/brew.sh

    # Step 4: Build project external libraries
    - name: Build C++ Libraries
      run: bash ./.github/workflows/build.sh

    # Step 5: Configure Xcode version
    - name: Select Xcode version
      run: |
        sudo xcode-select -switch /Applications/Xcode_26.2.app
        /usr/bin/xcodebuild -version
    # Run XCode tests with specific configurations:
    # - Builds and runs the test suite
    # - Generates code coverage reports
    # - Uses PostgreSQL and libpqxx external dependencies
    # - Outputs results in JUnit format
    - name: Run tests
      run: >
          OTHER_CFLAGS="-fprofile-instr-generate -fcoverage-mapping"
          OTHER_CPLUSPLUSFLAGS="-fprofile-instr-generate -fcoverage-mapping"
          OTHER_SWIFT_FLAGS="-profile-generate -profile-coverage-mapping"
          LLVM_PROFILE_FILE="/tmp/coverage.profraw"
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          xcodebuild
          -scheme tests
          -destination 'platform=macOS'
          -resultBundlePath TestResult/ 
          -enableCodeCoverage YES 
          -derivedDataPath "${RUNNER_TEMP}/Build/DerivedData" 
          HEADER_SEARCH_PATHS="./external/libpqxx/include/pqxx/internal ./external/libpqxx/include/ ./external/libpqxx/build/include/ ./external/"
          LIBRARY_SEARCH_PATHS="./external/libpqxx/src/ ./external/libpqxx/build/src/"
          OTHER_LDFLAGS="-L./external/libpqxx/build/src -lpqxx -lpq -L$(brew --prefix pkgconf)/lib -L$(brew --prefix pkgconf)/lib/pkgconfig -L$(brew --prefix postgresql@18)/lib/postgresql -L$(brew --prefix postgresql@18)/lib/postgresql/pgxs -L$(brew --prefix postgresql@18)/lib/postgresql/pkgconfig"
          clean build test
          | xcpretty -r junit && exit ${PIPESTATUS[0]}
    - name: Convert coverage report to sonarqube format
      run: >
          bash ./.github/workflows/xccov-to-sonarqube-generic.sh *.xcresult/ > sonarqube-generic-coverage.xml
    # Artifact will be available only for 1 day, this is because 
    # it's only used to pass test data to SonarCloud only
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        path: sonarqube-generic-coverage.xml
        retention-days: 1 # Artifact will be available only for 5 days.
        
  sonar-scan:    
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository on branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.HEAD_REF }}
          fetch-depth: 0       
      - name: Check compiler version, for debugging
        run: |
          g++ --version
          cmake --version
      - name: Build C++ Libraries
        run: >
            bash ./.github/workflows/build.sh
      - name: Install Python 3.12 for gcovr
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      # Gcovr provides a utility for managing the use of the GNU gcov utility and generating 
      # summarized code coverage results. This command is inspired by the Python coverage.py 
      # package, which provides a similar utility for Python.
      # https://pypi.org/project/gcovr/
      - name: Install gcovr
        run: |
          pip install gcovr==8.3
      # SonarQube Server and Cloud (formerly SonarQube and SonarCloud) is a widely used static 
      # analysis solution for continuous code quality and security inspection.
      # This action now supports and is the official entrypoint for scanning C++ projects via GitHub actions.
      # https://github.com/SonarSource/sonarqube-scan-action
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4.2.1 
        # This step installs the SonarQube build wrapper, which is necessary for analyzing C/C++ projects.
      
      # Downloads all artifacts generated by previous steps in the workflow
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      
      # Configures the CMake build system, specifying the source directory and build directory, and setting the build type
      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      # Runs the build wrapper to capture build commands and outputs them to the specified directory. Then builds the project using CMake
      - name: Run build-wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      # Performs the SonarQube scan using the scan action. Uses captured build commands for analysis and requires GitHub and SonarQube tokens for authentication
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }} 
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
            --define sonar.coverageReportPaths=artifact/sonarqube-generic-coverage.xml